[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
rocket = "0.5.0"

[dependencies.sea-orm-migration]
version = "1.0.0-rc.2" # sea-orm-migration version
features = ["sqlx-postgres"]
